### ISSUE TITLE
Create a real design

### ISSUE THREAD

**Issue by nasmal** [nasmal/localtradingapp#13]
Enhance the UI by designing elements of the brand.

**Comment by nasmal** [comment]
![Screen Shot 2020-03-24 at 11 15 06 PM](https://user-images.githubusercontent.com/15257495/77498746-c9b33900-6e26-11ea-81c9-f708c715bd94.png)
Example splash page/colors

**Comment by nasmal** [comment]
[Local Trading App.pdf](https://github.com/nasmal/localtradingapp/files/4389889/Local.Trading.App.pdf)

Updates & additions

**Comment by mingen-pan** [comment]
This is fantastic. Looks great!

**Comment by nasmal** [comment]
The new/edit pages that have forms function but have no styling yet - still a todo.
