### ISSUE TITLE
Markers on the map - like redfin.com using google maps

### ISSUE THREAD

**Issue by Gouthamkreddy1234** [nasmal/localtradingapp#19]
- need to implement the UI to add markers on a map for each item. 
- form submit when a seller posts an item carries a hidden argument that comprises the lat/long of the item which is later displayed on the map wher the map view is loaded.

**Comment by Gouthamkreddy1234** [comment]
The Google maps API does'nt look really hard. I think we can add it as a part of this iteration. I am taking a look at it right now.

**Comment by nasmal** [comment]
Will try to use this: https://github.com/apneadiving/Google-Maps-for-Rails

**Comment by nasmal** [comment]
This PR add basic google map with markers for sell posts: https://github.com/nasmal/localtradingapp/pull/25

**Comment by nasmal** [comment]
Marking as closed for iteration 2. Will need to open another maps related issue to expand on the feature for iteration 3.
