### ISSUE TITLE
Error when creating a sell post

### ISSUE THREAD

**Issue by nasmal** [nasmal/localtradingapp#20]
On the master branch I tried to create a sell post, but get the error "Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /Users/nathan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activestorage-5.2.4.1/app/models/active_storage/blob/analyzable.rb to define it"

Not sure how to fix this - maybe it is an easy fix? Screenshots:
![FireShot Capture 009 - Action Controller_ Exception caught - 0 0 0 0](https://user-images.githubusercontent.com/15257495/78295699-8d549c80-74fa-11ea-9b52-9278897ca870.png)
![FireShot Capture 010 -  - 0 0 0 0](https://user-images.githubusercontent.com/15257495/78295704-8f1e6000-74fa-11ea-933b-15aa07b2db8e.png)

**Comment by mingen-pan** [comment]
I don't have this issue. Could you try it without image first? Wanted to make sure which part causes this issue.

**Comment by nasmal** [comment]
Yes, it seems I get a different error now:

![FireShot Capture 011 - Action Controller_ Exception caught - 0 0 0 0](https://user-images.githubusercontent.com/15257495/78296417-bcb7d900-74fb-11ea-8188-2ab9a7a53de7.png)

**Comment by nasmal** [comment]
solved by deleting these two files

config/master.key
config/credentials.yml.enc

and then running

EDITOR="nano --wait" bin/rails credentials:edit
